# Generated by Django 2.0.5 on 2018-07-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_remove_courseorg_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, upload_to='org/%Y/%m', verbose_name='logo'),
        ),
    ]
