# Generated by Django 2.0.5 on 2018-07-26 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_teacher_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='course_nums',
        ),
    ]
