# Generated by Django 2.0.5 on 2018-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_courseorg_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_nums',
            field=models.CharField(default=0, max_length=100, verbose_name='课程数量'),
        ),
    ]
